(*
	Error message codes.  Encourages consistent and non-repeated codes.
*)

global ERR_AT_MIN_RESOLUTION
set ERR_AT_MIN_RESOLUTION to 500

global ERR_AT_MAX_RESOLUTION
set ERR_AT_MAX_RESOLUTION to 501

global ERR_UNKNOWN_RESOLUTION
set ERR_UNKNOWN_RESOLUTION to 502

global ERR_INVALID_RESOLUTION_REQUESTED
set ERR_INVALID_RESOLUTION_REQUESTED to 503
